export const AUCTION_INSTANCE = "AUCTION_INSTANCE";
export const TOKEN_INSTANCE = "TOKEN_INSTANCE";
export const CURRENT_ACCOUNT = "CURRENT_ACCOUNT";
export const METAMASK_STATUS = "METAMASK_STATUS";
export const METAMASK_CONNECT_FUNCTION = "METAMASK_CONNECT_FUNCTION";
export const NETWORK_ID = "NETWORK_ID";
export const LOAD = "LOAD";
